/** Fixed Basilisk stack IDs — do not renumber without Whitemane lock. */
export const BASILISK_SUBSYSTEMS = [
  {
    id: '0xB101',
    name: 'Serverine',
    role: 'Resident Intelligence & Studio Steward',
    detail: 'Resident face of NEXUS/BASILISK — parallel posture to Leyla on the HYDRA sibling. Concept mock only.',
    kind: 'resident',
  },
  {
    id: '0xB202',
    name: 'Jezebel Engine',
    role: 'Specialist Engine (not OS)',
    detail: 'Specialist engine — not the resident assistant and not an OS layer. Feeds Source/Persona on the TriCells line.',
    kind: 'specialist',
  },
  {
    id: '0xB303',
    name: 'Studio Factories TriCells',
    role: 'Production Line',
    detail: 'Source/Persona → Jezebel · Production · Packaging · Distribution · Analytics → Context Orbit',
    kind: 'factory',
    stages: [
      'Source / Persona → Jezebel',
      'Production',
      'Packaging',
      'Distribution',
      'Analytics → Context Orbit',
    ],
  },
  {
    id: '0xB404',
    name: 'Affiliate Network',
    role: 'Basilisk Affiliate Lane',
    detail: 'Basilisk-side affiliate property. Simulated roster only — no live partners.',
    kind: 'network',
  },
  {
    id: '0xB505',
    name: 'Black Vault',
    role: 'Basilisk Vault',
    detail: 'Distinct from HYDRA Shadow Vault. Separate DB / policy surface. Demo seal only.',
    kind: 'vault',
  },
  {
    id: '0xB606',
    name: 'Violet Crusade',
    role: 'Brand Property (one)',
    detail: 'One brand / property on Basilisk — not an OS layer, not a core, not a vault.',
    kind: 'property',
  },
  {
    id: '0xB707',
    name: 'Basilisk Context Orbit',
    role: 'Local Context Orbit',
    detail: 'Basilisk-local orbit — separate from HYDRA Context Orbit. Simulated adjacency only.',
    kind: 'orbit',
  },
  {
    id: '0xB808',
    name: 'Basilisk Dollhouse',
    role: 'Presentation Surface',
    detail: 'Basilisk-local dollhouse presentation. Concept draft — no live stages.',
    kind: 'dollhouse',
  },
]
